### PR TITLE
Fix for sample app.

### PR DESCRIPTION
**Pull request by dbainbridge**
Currently you can not select the first button in the sample app which caused some confusion when testing it.

### CODE REVIEW

**Comment by unixo** [comment]
Instead of removing a line, I'd like a call to NSLog or a docblock to explain the feature.

**Comment by dbainbridge** [comment]
The sample app already has:

```
[sideBarDefault setTarget:self withSelector:@selector(logThis:) atIndex:0];
```

And in logThis it is still calling NSLog to show that the method was called.  But logThis also called selectNext which prevented that button at index 0 from ever being selected.  Which looks like a bug when running the sample app.   But perhaps I'm not understanding what you are trying to say :)

**Comment by unixo** [comment]
I simply suggested not to remove the call to `selectNext` in method `logThis:`, but to add some comments to the source code (or more detailed logging) that describes the behavior.
For example: `NSLog(@"First button has been pressed, but I'm gonna select next");`

**Comment by erndev** [comment]
@dbainbridge Thanks for the fix. i've pushed it to master.
Don't know why that "selectNext" line was there in the first place...  Maybe was testing something and forgot to delete it.

**Pull request merged**
